### ISSUE TITLE
Incomplete base url in generated links

### ISSUE THREAD

**Issue by abought** [statgen/LDServer#1]
## Description
The `next` link in LD payload seems to have the wrong base url.  This affects use of pagination links.

## Steps to reproduce
Sample URL with payload:
`http://portaldev.sph.umich.edu/ld/references/1000G_GRCh37/populations/ALL/regions?chrom=1&correlation=r&stop=114759349&variant=10:114758349_C/T&start=114755349&last=16911446074:8:3:1`

returns

`"next":"http://portaldev.sph.umich.edu/references/1000G_GRCh37/populations/ALL/regions?chrom=1&correlation=r&stop=114759349&variant=10:114758349_C/T&start=114755349&last=16911446074:8:3:1"`

The correct base url for this deployment is `/ld/references`.

**Comment by dtaliun** [comment]
Problem occurred when running app behind Apache mod_proxy. 
Also note that variant query starts with `/variants?`.

**Comment by abought** [comment]
> Problem occurred when running app behind Apache mod_proxy.
> Also note that variant query starts with `/variants?`.

Thanks. Confirmed `next` links are working correctly now, and obeying pagination with `limit` param.
