### ISSUE TITLE
General REST API notes/ first impressions

### ISSUE THREAD

**Issue by abought** [statgen/LDServer#6]
# Purpose/scope
Separate from the previous bug reports, below are some more general notes from first usage of the LD server API. Apologies for the info dump- these are from my notebook. Feel free to triage and separate the elements of this ticket as necessary. Each of these comments represents non-binding feedback for one particular use case.

I have divided these notes into several sections, based on how hard it would be to change things once the server was in active use.

**URLs/ semantics (possible breaking changes)**
- General: Writing code to consume an API is generally easier if the endpoints obey consistent rules.  Two examples in LDServer come to mind:
  - More consistent response payload format would be helpful. Eg "variant LD" returns data under `data:`; "references" meta endpoint data returns an array of objects at the top level; "population" meta endpoint returns an array of strings.
    - Returning under `data` is a useful convention, because it leaves room at the top level for other keys (like `error` or `meta`). If the payload is consistent, it's easier to write reusable front end code for parsing results or showing error messages.
  - Where possible, consistent nomenclature across endpoints is also helpful. Example: In the LD server, the query params are named chrom / start/stop, but Portaldev api uses chrom/start/end
    - Caveat: if the prior existing standard is bad, don't feel obligated to conform to it!
- There doesn't seem to be a good API mechanism for specifying genome build as a first-class concept. 
  - Currently, build seems to be part of a string name (1000G_GRCh37), but there is no guarantee that every panel will follow this convention. 
  - Example use case: for LocusZoom, I could imagine wanting a global "genome_build" config setting (specified  independent of reference panel, because other datasources would also depend on build).  The current mechanism of specifying build is fragile: https://github.com/statgen/locuszoom/pull/149/files#diff-a6139e2504656ffc08c847116c79ce29R848
    - Not every panel will obey this naming convention. This means that LZ datasource would need to either: a) hit the metadata endpoint on every page load (no way to guess "build-specific" panel name systematically), or b) hardcode a list of known "panel/build" names into my front-end code (lacks flexibility).

**Response formatting (tweaks that could be made later)**
- In my variant query, the variant1 field does not seem especially useful (always same value?) Response can be 1-2MB in size; a way to slim the payload would be "nice to have".
  - Alternatives include limiting what fields get returned, or perhaps a "meta" section for information that is constant across the entire request.
- Malformed requests currently return a 422 status code, but no explanation of the problem. This is especially confusing in the case of required query params that don't have default values. Ideally, the error payload should offer information about the validation error.

**Other notes**
- The canonical LZ example plot requires 2 pages of LD data, even using grch37-ALL (a relatively "small" set of variants). Is the pagination limit too low to accommodate a common use case?
  - Alternately, are current LocusZoom plots too wide? We should be sure that the final design does not place undue load on the LD server.
- In the above scenario, the  response is ~1.4MB of data, split across two pages. Would gzip encoding etc be useful? Have we explored this? (eg configured at the server level)

**API playground**
- The chromosome dropdown is a preset list (1-22), but it may be missing some options relevant to a panel. Here is an example request that seems to provide info for the X chromosome: http://portaldev.sph.umich.edu/ld/references/1000G_GRCh37/populations/ALL/regions?correlation=r&variant=10:114758349_C/T&chrom=X&start=114753349&stop=114759349
  - If the list of chromosomes is panel specific, perhaps this should be included as part of the panel-metadata endpoint?
- The current URL does not make it clear that the playground feature is related to the LD server. http://portaldev.sph.umich.edu/playground
- If a parameter has a default value (like "limit"), consider displaying showing that to the user.
- There should be some mechanism to help the user troubleshoot a bad request (unreasonable limit, bad variant name, etc). Two options are front end validation (before the request), or implementing API error payloads on the backend and showing the failure reason in the UI (after the request).

**Comment by dtaliun** [comment]
Addressed most of the comments

**Comment by abought** [comment]
My sincere apologies for the delay in looking at this; I really appreciate your work on the new LD server. I'm going to keep integrating it into LZ.js, and this is really turning into something that we're happy to recommend to our external collaborators.

The comments below are optional and all minor polish- feel free to assign any playground changes to me.  I think the core functionality is all there, and these comments are about helping people use it.

Towards that end, I tested the new error messages you added- very helpful. Thanks!

## Metadata endpoints
Use case: I would like to imagine building a UI ("choose LD source"), by fetching the options from the API. It would be nice to get all the data together in as few requests as practical.
- Currently there are 3 metadata "list view" endpoints for any particular dataset (builds / references / panels). Would it make sense to consolidate these into two API endpoints?
  - List view: all metadata known, grouped by panel (`/ld/panels`)
  - Detail view, when you have a single item in mind- eg `/ld/panels/1000G`

Here is a sample API payload to demonstrate:
```
{
    "data": [
        {
            "description": "1000 Genomes Project Phase 3",
            "name": "1000G",
            "builds": [  // This could just as easily be an array; maybe builds have metadata, but I have no idea whether it's useful in this context
                { "name": "GRCh38", "version": 12 }  
            ],
            "populations": [
                { "name": "AFR", "description": "African" },
                { "name": "EUR", "description": "European" },
                { "name": "ALL", "description": "All"}
            ]
        }
    ],
    "next": null,
    "error": null
}
```


## Playground/ API Explorer
References the URL https://portaldev.sph.umich.edu/playground
- Consider using protocol-relative URLs (`//portaldev.sph.umich.edu`) for the requests. When I load the playground over HTTPS, none of the sample requests work due to the following error:
`Mixed Content: The page at 'https://portaldev.sph.umich.edu/playground' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://portaldev.sph.umich.edu/ld/genome_builds'. This request has been blocked; the content must be served over HTTPS.`

  - _Reason_: many browsers are increasingly pushing https everywhere. We don't want to break the playground if someone deploys it according to best practices!

- Rather than being mounted as a separate service, would it make sense to optionally activate these routes under `/ld/playground`, based on a config option?
  - _Reason_: make it easier to run the LDServer as a single cohesive unit, underneath a shared hostname that runs multiple services (much like portaldev). 
  - I agree that not every end user will want an API explorer UI; a config option would offer a compromise.

- Could we sort the chromosomes dropdown? I realize this is VERY trivial, but....
![screen shot 2018-11-16 at 10 57 57 am](https://user-images.githubusercontent.com/2957073/48632299-9210c300-e98e-11e8-880c-3c09adbaa03d.png)

**Comment by abought** [comment]
Also, Peter has asked if the data ingestion process can ensure that there is always a population called "ALL"? 

This would help us to write standardized data sources, by providing a known default value that would work consistently for any dataset.

**Comment by dtaliun** [comment]
Yes, the "ALL" is ensured by implementation.
